[package]
name = "flexi"
version = "0.2.0"
edition = "2021"
description = "A minimal CLI tool for tracking your flexi-time balance"
license = "MIT"
repository = "https://github.com/thombruce/flexi"
keywords = ["flexi", "time", "cli", "productivity"]
categories = ["command-line-utilities"]

[[bin]]
name = "flexi"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
