[package]
name = "flexi"
version = "0.9.0"
edition = "2021"
description = "A minimal CLI tool for tracking your flexi-time balance"
license = "MIT"
repository = "https://github.com/thombruce/flexi"
keywords = ["flexi", "time", "cli", "productivity"]
categories = ["command-line-utilities"]

[[bin]]
name = "flexi"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = "0.4"
arboard = "3"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
dirs = "5"
owo-colors = { version = "4", features = ["supports-colors"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
